FROM adminer

RUN curl -o adminer.css https://raw.githubusercontent.com/eichters/adminer-dark-material-theme/master/adminer.css

RUN mkdir src

RUN curl -o src/check.svg https://raw.githubusercontent.com/eichters/adminer-dark-material-theme/master/src/check.svg
RUN curl -o src/radio.svg https://raw.githubusercontent.com/eichters/adminer-dark-material-theme/master/src/radio.svg
